import Head from "next/head";
import Hero from "../components/Hero";
import Header from "../components/Header";
import SmallCard from "../components/SmallCard";
import MediumCard from "../components/MediumCard";

export default function Home({ exploreData, cardsData }) {
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Hero />

      <main className="max-w-7xl mx-auto px-8 sm:px-16">
        <section>
          <h2 className="text-4xl font-semibold py-5">
            Inspiration for your next trip
          </h2>

          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">
            {exploreData?.map(({ img, distance, location }) => (
              <SmallCard
                key={img}
                img={img}
                distance={distance}
                location={location}
              />
            ))}
          </div>
        </section>

        <section>
          <h2 className="text-4xl font-semibold py-8">Live Anywhere</h2>

          <div className="flex space-x-3 overflow-scroll scrollbar-hide p-3 -ml-3">
            {cardsData?.map(({ img, title }) => (
              <MediumCard key={img} img={img} title={title} />
              ))}
          </div>

        </section>
      </main>
    </div>
  );
}

//Happens when client request hits server, before page data is sent back to client, then data is passed to components as props
export async function getStaticProps() {
  const exploreData = await fetch(
    "https://airbnb-32bf6-default-rtdb.firebaseio.com/locations.json",
  ).then((res) => res.json());
  console.log(exploreData);

  const cardsData = await fetch('https://airbnb-32bf6-default-rtdb.firebaseio.com/mediumCard.json')
  .then(res => res.json());
  console.log(cardsData)


  //Gets passed to the Home component after build as props
  return {
    props: {
      exploreData,
      cardsData
    },
  };
}
